#TWO TYPES OF TYPE CONEVERSIONS
#TYPE CONVERSION=CONVERTING ONE DATA TYPE TO ANOTHER DATA TYPE
#1. IMPLICIT TYPE CONVERSION
#2. EXPLICIT TYPE CONVERSION

#1. IMPLICIT TYPE CONVERSION:
#python automatically converts one data type to another data type
#INBUILT FUNCTION

#1.EXPLICIT TYPE CONVERSION:
#we can convert one data type to another data type using inbuilt functions
#USER DEFINED FUNCTION
#int(),float(),str(),complex(),bin(),oct(),hex()
#int(n),float(n),str(n),complex(n),bin(n),oct(n),hex(n)
#EXAMPLE FOR IMPLICIT TYPE CONVERSION:
name=input("what is your name?")
age=int(input("what is your age?"))
print(f"Hello {name}! You are {age} years old.")